# Generated by Django 3.0.12 on 2021-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
